= Node.js Beyond the Basics
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :bookmark:
:important-caption: :boom:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

**The navigable website for this book is at https://jscomplete.com/learn/node-beyond-basics[jscomplete.com/node-beyond-basics]**

WARNING: This book is still a work in progress. New content is synced here as it gets ready.

=== Getting Help

We use Slack chat for support. You can use the form at https://jscomplete.com/help[jscomplete.com/help^] to get an email invite.

=== Contributing

You can click the "Edit this file" pencil icon while reading any of the lessons under this book, and then make any edits and push the green "Commit changes" button.

All contributions are welcome, even if it was just to correct a tiny typo or code formatting issue, or even to add a comma. Please know that if you contribute to this book, you're contributing to our efforts to fight racial injustice everywhere, and we will be in deep gratitude to you.

The chapters are written in AsciiDoc, which is just like Markdown but with standards and a lot more features. See https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[this syntax reference guide^] for a quick start.
